### PR TITLE
Create blank.yml

### PR DESCRIPTION
**Pull request by yopyozzi27**
From 67c0afc1da354d8571f51b6f0af8f2794117fd10 Mon Sep 17 00:00:00 2001
From: The Octocat <octocat@nowhere.com>
Date: Sun, 27 Apr 2014 15:36:39 +0530
Subject: [PATCH] updated index for better welcome message

---
 index.html | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/index.html b/index.html
index 35a7409..4643085 100644
--- a/index.html
+++ b/index.html
@@ -18,8 +18,8 @@
         <header class="inner">
           <a id="forkme_banner" href="https://github.com/octocat">View on GitHub</a>
 
-          <h1 id="project_title">Octocat.github.io</h1>
-          <h2 id="project_tagline"></h2>
+          <h1 id="project_title">Welome to the Octocat homepage!</h1>
+          <h2 id="project_tagline">Be sure to keep this page in mind to see all my latest updates.</h2>
 
         </header>
     </div>

### CODE REVIEW

**Comment by ghost** [comment]
Fuck off

**Comment by xXxrAinZyian** [comment]
Ok

**Comment by xXxrAinZyian** [comment]
Sorry

**Review by yaSinc69 — APPROVED** [review]

**Comment by Jeremias1229** [comment]
`.patch`

**Review by Jeremias1229 — APPROVED** [review]

**Comment by Jeremias1229** [comment]
Commin .diff

**Comment by supersonictw** [comment]
Junk

**Pull request closed without merging**
